---
"SISESTAKAART":
  frontpage: true
  title: Palun sisesta kaart
  b1:
    label: null
    go: null
  b2:
    label: null
    go: null
  b3:
    label: null
    go: null
  b4:
    label: null
    go: null
  b5:
    label: null
    go: null
  b6:
    label: null
    go: null
  b7:
    label: null
    go: null
  b8:
    label: "Jätka"
    go: "PIN"
"PIN":
  title: "Sisesta PIN:"
  b1:
    label: null
    go: null
  b2:
    label: null
    go: null
  b3:
    label: null
    go: null
  b4:
    label: "Katkesta"
    go: "LÕPETA"
  b5:
    label: null
    go: null
  b6:
    label: null
    go: null
  b7:
    label: null
    go: null
  b8:
    label: "Jätka"
    go: "ESILEHT"
"ESILEHT":
  title: "Palun valige toiming"
  b1:
    label: null
    go: null
  b2:
    label: null
    go: null
  b3:
    label: null
    go: null
  b4:
    label: "Kaardi tagastamine"
    go: "LÕPETA"
  b5:
    label: null
    go: null
  b6:
    label: null
    go: null
  b7:
    label: null
    go: null
  b8:
    label: null
    go: null
"LÕPETA":
  title: "Eemalda kaart"
  title_en: "Remove the Card" 
  b1:
    label: null
    go: null
  b2:
    label: null
    go: null
  b3:
    label: null
    go: null
  b4:
    label: null
    go: null
  b5:
    label: null
    go: null
  b6:
    label: null
    go: null
  b7:
    label: null
    go: null
  b8:
    label: null
    go: null
  timer:
    time: 4000
    go: "SISESTAKAART"
